version: "3.8.6"
services:
  app:
    container_name: inside-demo-project
    image: inside-demo-project
    build: ./
    restart: always
    ports:
      - "2345:2345"mvn -version
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/insideDB
  postgres_db:
    image: "postgres:11.4"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MasterKey6
      POSTGRES_DB: insideDB