version: "3.8"
services:
  app:
    container_name: "InsideDemo_container"
    image: "sibugato/inside-demo-project"
    restart: always
    ports:
      - "2345:2345"
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/insideDB
  postgres_db:
    image: "postgres:14.5"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MasterKey6
      POSTGRES_DB: insideDB
